apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: amt-tiltak-v1
  namespace: amt
  labels:
    team: amt
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete # delete = ingen compaction
    retentionHours: -1 # evig retention
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 2
  acl:
    - team: amt
      application: amt-arena-acl
      access: write
    - team: amt
      application: amt-tiltak
      access: read
