apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: deltaker-endring-v1
  namespace: amt
  labels:
    team: amt
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    retentionHours: 720
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 2
  acl:
    - team: amt
      application: amt-deltaker-bff
      access: write
    - team: amt
      application: amt-tiltak
      access: read
    - team: amt
      application: amt-kafka-manager
      access: read
