apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: deltaker-ekstern-v1
  namespace: amt
  labels:
    team: amt
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    retentionHours: -1
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 2
  acl:
    - team: amt
      application: amt-deltaker
      access: write
    - team: amt
      application: amt-kafka-manager
      access: read
    - team: teamoppfolging
      application: dvh-arb-tiltak-deltaker-konsument
      access: read
    - team: team-mulighetsrommet
      application: mulighetsrommet-api
      access: read
    - team: team-mulighetsrommet
      application: mulighetsrommet-kafka-manager
      access: read
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
    - team: teamoppfolging
      application: teamoppfolging-kafka-manager
      access: read
    - team: team-mulighetsrommet
      application: tiltakshistorikk
      access: read
    - team: tpts
      application: tiltakspenger-saksbehandling-api
      access: read
