apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: deltaker-v2
  namespace: amt
  labels:
    team: amt
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
spec:
  pool: nav-dev
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 2
  acl:
    - team: amt
      application: amt-tiltak
      access: write
    - team: amt
      application: amt-kafka-manager
      access: read
    - team: amt
      application: amt-tiltaksarrangor-bff
      access: read
    - team: teamoppfolging
      application: dvh-arb-tiltak-deltaker-konsument
      access: read
    - team: team-mulighetsrommet
      application: mulighetsrommet-api
      access: read
    - team: team-mulighetsrommet
      application: mulighetsrommet-kafka-manager
      access: read
    - team: teamoppfolging
      application: teamoppfolging-kafka
      access: read
    - team: amt
      application: amt-aktivitetskort-publisher
      access: read
    - team: amt
      application: amt-arrangor
      access: read
