kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: amt-kafka-manager
  namespace: amt
  labels:
    team: amt
spec:
  image: ghcr.io/navikt/kafka-manager/kafka-manager:2.2021.09.28_14.02-a4df79a588ab
  port: 8080
  webproxy: true
  ingresses:
    - https://amt-kafka-manager.dev.intern.nav.no
  prometheus:
    enabled: true
    path: /internal/prometheus
  readiness:
    path: /internal/health/readiness
    initialDelay: 20
  liveness:
    path: /internal/health/liveness
    initialDelay: 20
  replicas:
    min: 1
    max: 1  # 1 instance is required since in-memory session management is used
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        groups:
          - id: 0a84d77e-c8e9-4173-96af-164eb7fbb749
  kafka:
    pool: nav-dev
  env:
    - name: APP_CONFIG_JSON
      value: >
        {
          "topics": [
            {
              "name": "amt.test-arena-tiltak",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "amt.test-arena-tiltaksgruppe",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "amt.test-arena-tiltaksgjennomforing",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            },
            {
              "name": "amt.test-arena-tiltakdeltaker",
              "location": "AIVEN",
              "keyDeserializerType": "STRING",
              "valueDeserializerType": "STRING"
            }
          ]
        }
