apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: deltaker-v1
  namespace: amt
  labels:
    team: amt
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 3
  acl:
    - team: amt
      application: amt-tiltak
      access: write
    - team: amt
      application: amt-kafka-manager
      access: read
    - team: teamoppfolging
      application: dvh-arb-tiltak-deltakerliste-konsument
      access: read
