apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: nav-enhet-v1
  namespace: amt
  labels:
    team: amt
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 2
  acl:
    - team: amt
      application: amt-tiltak
      access: readwrite
    - team: amt
      application: amt-kafka-manager
      access: read
