apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: nav-bruker-personalia-v1
  namespace: amt
  labels:
    team: amt
spec:
  pool: nav-prod
  config:
    cleanupPolicy: compact
    minimumInSyncReplicas: 2
    partitions: 4
    replication: 3
  acl:
    - team: amt
      application: amt-person-service
      access: write
    - team: amt
      application: amt-kafka-manager
      access: read
    - team: amt
      application: amt-tiltak
      access: read
    - team: amt
      application: amt-deltaker-bff
      access: read
    - team: amt
      application: amt-deltaker
      access: read
