apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  annotations:
    nais.io/security-does-not-matter: "true"
  name: amt-tiltaksansvarlig-flate-auth-proxy-redis
  namespace: amt
  labels:
    team: amt
spec:
  image: bitnami/redis:6.2-debian-10
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  envFrom:
  - secret: amt-tiltaksansvarlig-flate-auth-proxy-redis-secret
  accessPolicy:
    inbound:
      rules:
        - application: amt-tiltaksansvarlig-flate-auth-proxy
